### ISSUE TITLE
Add Indeed job board

### ISSUE THREAD

**Issue by kaanyagci** [Makepad-fr/job-finder#2]
We can get all job announcements from Indeed from https://www.indeed.com/browsejobs URL.
We need to use the same scraper code for each country that we can get from https://www.indeed.com/worldwide

## TODOs

- [ ] Create an Indeed class that contains the base scraper code which can run for an Indeed website.
- [ ] In that class create a function to get the list of the countries that Indeed is available
- [ ] Update the Job class. The Job class should contain also the country for the job
- [ ] Update the WWR parser to get the country of the jobs
